export const useGetQuoteDetails = (quoteReference: string) => {
  // Simulate API fetch returning all data in one response
  return {
    data: {
      employer: {
        companyName: "Meridian Logistics (Pty) Ltd",
        brokerage: "Kenn Brokerage",
        employerDetails: [
          { label: "Employer Name", value: "10102" },
          { label: "Registration Number", value: "2012/098431/07" },
          { label: "Industry", value: "Mining" },
          { label: "Province", value: "Gauteng" },
          { label: "Broker Name", value: "Apex Brokerage Services" },
          { label: "Inception Date", value: "01-08-2026" },
        ],
        contactDetails: [
          { label: "Full Name", value: "Ayanda Khumalo" },
          { label: "Phone Number", value: "011 234 5678" },
          { label: "Email", value: "ayanda@pinnaclebrokers.co.za" },
        ],
        quoteDetails: [
          {
            label: "Quote Reference",
            value: quoteReference || "QT-202605-002",
          },
          { label: "Quote Date", value: "18-07-2026" },
          { label: "Pricing Source", value: "Quote" },
          { label: "Pricing Date", value: "19-07-2026" },
          { label: "Approval Reference", value: "APP-2026-8809" },
          { label: "Validity", value: "Valid" },
          { label: "Quote Acceptance Date", value: "20-05-2026" },
          { label: "Quote Status", value: "Approved" },
        ],
      },
      employees: [
        {
          id: "8804155032082",
          name: "Thabo Sipho Nkosi",
          dob: "05-05-1985",
          phone: "072 312 4455",
          email: "thabo.nkosi@gmail.com",
          method: "Email",
          incept: "01-08-2026",
          premium: "R 200.00",
          vopd: "Verified",
          aml: "Clear : Low Risk",
        },
        {
          id: "8804155032083",
          name: "John doe",
          dob: "05-05-1985",
          phone: "072 312 4455",
          email: "John@gmail.com",
          method: "Email",
          incept: "01-08-2026",
          premium: "R 200.00",
          vopd: "Verified",
          aml: "Clear : Low Risk",
        },
        {
          id: "8804155032084",
          name: "John Williamsion",
          dob: "05-05-1985",
          phone: "072 312 4455",
          email: "williamson@gmail.com",
          method: "Email",
          incept: "01-08-2026",
          premium: "R 200.00",
          vopd: "Verified",
          aml: "Clear : Low Risk",
        },
        {
          id: "8804155032085",
          name: "Cane Cone",
          dob: "05-05-1985",
          phone: "072 312 4455",
          email: "cone@gmail.com",
          method: "Email",
          incept: "01-08-2026",
          premium: "R 200.00",
          vopd: "Verified",
          aml: "Clear : Low Risk",
        },
        {
          id: "8804155032086",
          name: "Moto Sibanye",
          dob: "05-05-1985",
          phone: "072 312 4455",
          email: "moto@gmail.com",
          method: "Email",
          incept: "01-08-2026",
          premium: "R 200.00",
          vopd: "Verified",
          aml: "Clear : Low Risk",
        },
        {
          id: "8804155032087",
          name: "Exxaro David",
          dob: "05-05-1985",
          phone: "072 312 4455",
          email: "exxaro@gmail.com",
          method: "Email",
          incept: "01-08-2026",
          premium: "R 200.00",
          vopd: "Verified",
          aml: "Clear : Low Risk",
        },
      ],
      variance: [
        { label: "Quoted Member Count", value: "40" },
        { label: "Validated Member Count", value: "28" },
        { label: "Calculated Variance Rate", value: "62.5%" },
      ],
    },
    isLoading: false,
  };
};
